/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.desoftmex.control;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Default;
import javax.faces.bean.ApplicationScoped;
import javax.faces.model.SelectItem;
import javax.faces.model.SelectItemGroup;
import javax.inject.Named;

/**
 *
 * @author Gustavo
 */
@Named
@SessionScoped
//@ApplicationScoped
public class SessionBean implements Serializable{
    
    private Map<String,String> listStatus;
    private Map<String,String> tiposMenus;
    
    private List<Icono> listIconos;
    
    @PostConstruct
    public void init(){
        setIconos();
        setStatus();
        setTipoMenus();
    }    

    public List<Icono> getListIconos() {
        return listIconos;
    }

    public Map<String,String> getListStatus() {
        return listStatus;
    }

    public Map<String, String> getTiposMenus() {
        return tiposMenus;
    }      
    
    
    /**
     * Se llena la lista de los iconos
     */
    private void setIconos(){
        listIconos = new ArrayList<Icono>();
        listIconos.add(new Icono(0, "icon-home               ","home               "));
        listIconos.add(new Icono(1, "icon-newspaper          ","newspaper          "));
        listIconos.add(new Icono(2, "icon-pencil             ","pencil             "));
        listIconos.add(new Icono(3, "icon-droplet            ","droplet            "));
        listIconos.add(new Icono(4, "icon-pictures           ","pictures           "));
        listIconos.add(new Icono(5, "icon-camera             ","camera             "));
        listIconos.add(new Icono(6, "icon-music              ","music              "));
        listIconos.add(new Icono(7, "icon-film               ","film               "));
        listIconos.add(new Icono(8, "icon-camera-2           ","camera-2           "));
        listIconos.add(new Icono(9, "icon-spades             ","spades             "));
        listIconos.add(new Icono(10, "icon-clubs              ","clubs              "));
        listIconos.add(new Icono(11, "icon-diamonds           ","diamonds           "));
        listIconos.add(new Icono(12, "icon-broadcast          ","broadcast          "));
        listIconos.add(new Icono(13, "icon-mic                ","mic                "));
        listIconos.add(new Icono(14, "icon-book               ","book               "));
        listIconos.add(new Icono(15, "icon-file               ","file               "));
        listIconos.add(new Icono(16, "icon-new                ","new                "));
        listIconos.add(new Icono(17, "icon-copy               ","copy               "));
        listIconos.add(new Icono(18, "icon-folder             ","folder             "));
        listIconos.add(new Icono(19, "icon-folder-2           ","folder-2           "));
        listIconos.add(new Icono(20, "icon-tag                ","tag                "));
        listIconos.add(new Icono(21, "icon-cart               ","cart               "));
        listIconos.add(new Icono(22, "icon-basket             ","basket             "));
        listIconos.add(new Icono(23, "icon-calculate          ","calculate          "));
        listIconos.add(new Icono(24, "icon-support            ","support            "));
        listIconos.add(new Icono(25, "icon-phone              ","phone              "));
        listIconos.add(new Icono(26, "icon-mail               ","mail               "));
        listIconos.add(new Icono(27, "icon-location           ","location           "));
        listIconos.add(new Icono(28, "icon-compass            ","compass            "));
        listIconos.add(new Icono(29, "icon-history            ","history            "));
        listIconos.add(new Icono(30, "icon-clock              ","clock              "));
        listIconos.add(new Icono(31, "icon-bell               ","bell               "));
        listIconos.add(new Icono(32, "icon-calendar           ","calendar           "));
        listIconos.add(new Icono(33, "icon-printer            ","printer            "));
        listIconos.add(new Icono(34, "icon-mouse              ","mouse              "));
        listIconos.add(new Icono(35, "icon-screen             ","screen             "));
        listIconos.add(new Icono(36, "icon-laptop             ","laptop             "));
        listIconos.add(new Icono(37, "icon-mobile             ","mobile             "));
        listIconos.add(new Icono(38, "icon-cabinet            ","cabinet            "));
        listIconos.add(new Icono(39, "icon-drawer             ","drawer             "));
        listIconos.add(new Icono(40, "icon-drawer-2           ","drawer-2           "));
        listIconos.add(new Icono(41, "icon-box                ","box                "));
        listIconos.add(new Icono(42, "icon-box-add            ","box-add            "));
        listIconos.add(new Icono(43, "icon-box-remove         ","box-remove         "));
        listIconos.add(new Icono(44, "icon-download           ","download           "));
        listIconos.add(new Icono(45, "icon-upload             ","upload             "));
        listIconos.add(new Icono(46, "icon-database           ","database           "));
        listIconos.add(new Icono(47, "icon-flip               ","flip               "));
        listIconos.add(new Icono(48, "icon-flip-2             ","flip-2             "));
        listIconos.add(new Icono(49, "icon-undo               ","undo               "));
        listIconos.add(new Icono(50, "icon-redo               ","redo               "));
        listIconos.add(new Icono(51, "icon-forward            ","forward            "));
        listIconos.add(new Icono(52, "icon-reply              ","reply              "));
        listIconos.add(new Icono(53, "icon-reply-2            ","reply-2            "));
        listIconos.add(new Icono(54, "icon-comments           ","comments           "));
        listIconos.add(new Icono(55, "icon-comments-2         ","comments-2         "));
        listIconos.add(new Icono(56, "icon-comments-3         ","comments-3         "));
        listIconos.add(new Icono(57, "icon-comments-4         ","comments-4         "));
        listIconos.add(new Icono(58, "icon-comments-5         ","comments-5         "));
        listIconos.add(new Icono(59, "icon-user               ","user               "));
        listIconos.add(new Icono(60, "icon-user-2             ","user-2             "));
        listIconos.add(new Icono(61, "icon-user-3             ","user-3             "));
        listIconos.add(new Icono(62, "icon-busy               ","busy               "));
        listIconos.add(new Icono(63, "icon-loading            ","loading            "));
        listIconos.add(new Icono(64, "icon-loading-2          ","loading-2          "));
        listIconos.add(new Icono(65, "icon-search             ","search             "));
        listIconos.add(new Icono(66, "icon-zoom-in            ","zoom-in            "));
        listIconos.add(new Icono(67, "icon-zoom-out           ","zoom-out           "));
        listIconos.add(new Icono(68, "icon-key                ","key                "));
        listIconos.add(new Icono(69, "icon-key-2              ","key-2              "));
        listIconos.add(new Icono(70, "icon-locked             ","locked             "));
        listIconos.add(new Icono(71, "icon-unlocked           ","unlocked           "));
        listIconos.add(new Icono(72, "icon-wrench             ","wrench             "));
        listIconos.add(new Icono(73, "icon-equalizer          ","equalizer          "));
        listIconos.add(new Icono(74, "icon-cog                ","cog                "));
        listIconos.add(new Icono(75, "icon-pie                ","pie                "));
        listIconos.add(new Icono(76, "icon-bars               ","bars               "));
        listIconos.add(new Icono(77, "icon-stats-up           ","stats-up           "));
        listIconos.add(new Icono(78, "icon-gift               ","gift               "));
        listIconos.add(new Icono(79, "icon-trophy             ","trophy             "));
        listIconos.add(new Icono(80, "icon-diamond            ","diamond            "));
        listIconos.add(new Icono(81, "icon-coffee             ","coffee             "));
        listIconos.add(new Icono(82, "icon-rocket             ","rocket             "));
        listIconos.add(new Icono(83, "icon-meter-slow         ","meter-slow         "));
        listIconos.add(new Icono(84, "icon-meter-medium       ","meter-medium       "));
        listIconos.add(new Icono(85, "icon-meter-fast         ","meter-fast         "));
        listIconos.add(new Icono(86, "icon-dashboard          ","dashboard          "));
        listIconos.add(new Icono(87, "icon-fire               ","fire               "));
        listIconos.add(new Icono(88, "icon-lab                ","lab                "));
        listIconos.add(new Icono(89, "icon-remove             ","remove             "));
        listIconos.add(new Icono(90, "icon-briefcase          ","briefcase          "));
        listIconos.add(new Icono(91, "icon-briefcase-2        ","briefcase-2        "));
        listIconos.add(new Icono(92, "icon-cars               ","cars               "));
        listIconos.add(new Icono(93, "icon-bus                ","bus                "));
        listIconos.add(new Icono(94, "icon-cube               ","cube               "));
        listIconos.add(new Icono(95, "icon-cube-2             ","cube-2             "));
        listIconos.add(new Icono(96, "icon-puzzle             ","puzzle             "));
        listIconos.add(new Icono(97, "icon-glasses            ","glasses            "));
        listIconos.add(new Icono(98, "icon-glasses-2          ","glasses-2          "));
        listIconos.add(new Icono(99, "icon-accessibility      ","accessibility      "));
        listIconos.add(new Icono(100, "icon-accessibility-2    ","accessibility-2    "));
        listIconos.add(new Icono(101, "icon-target             ","target             "));
        listIconos.add(new Icono(102, "icon-target-2           ","target-2           "));
        listIconos.add(new Icono(103, "icon-lightning          ","lightning          "));
        listIconos.add(new Icono(104, "icon-power              ","power              "));
        listIconos.add(new Icono(105, "icon-power-2            ","power-2            "));
        listIconos.add(new Icono(106, "icon-clipboard          ","clipboard          "));
        listIconos.add(new Icono(107, "icon-clipboard-2        ","clipboard-2        "));
        listIconos.add(new Icono(108, "icon-playlist           ","playlist           "));
        listIconos.add(new Icono(109, "icon-grid-view          ","grid-view          "));
        listIconos.add(new Icono(110, "icon-tree-view          ","tree-view          "));
        listIconos.add(new Icono(111, "icon-cloud              ","cloud              "));
        listIconos.add(new Icono(112, "icon-cloud-2            ","cloud-2            "));
        listIconos.add(new Icono(113, "icon-download-2         ","download-2         "));
        listIconos.add(new Icono(114, "icon-upload-2           ","upload-2           "));
        listIconos.add(new Icono(115, "icon-upload-3           ","upload-3           "));
        listIconos.add(new Icono(116, "icon-link               ","link               "));
        listIconos.add(new Icono(117, "icon-link-2             ","link-2             "));
        listIconos.add(new Icono(118, "icon-flag               ","flag               "));
        listIconos.add(new Icono(119, "icon-flag-2             ","flag-2             "));
        listIconos.add(new Icono(120, "icon-attachment         ","attachment         "));
        listIconos.add(new Icono(121, "icon-eye                ","eye                "));
        listIconos.add(new Icono(122, "icon-bookmark           ","bookmark           "));
        listIconos.add(new Icono(123, "icon-bookmark-2         ","bookmark-2         "));
        listIconos.add(new Icono(124, "icon-star               ","star               "));
        listIconos.add(new Icono(125, "icon-star-2             ","star-2             "));
        listIconos.add(new Icono(126, "icon-star-3             ","star-3             "));
        listIconos.add(new Icono(127, "icon-heart              ","heart              "));
        listIconos.add(new Icono(128, "icon-heart-2            ","heart-2            "));
        listIconos.add(new Icono(129, "icon-thumbs-up          ","thumbs-up          "));
        listIconos.add(new Icono(130, "icon-thumbs-down        ","thumbs-down        "));
        listIconos.add(new Icono(131, "icon-plus               ","plus               "));
        listIconos.add(new Icono(132, "icon-minus              ","minus              "));
        listIconos.add(new Icono(133, "icon-help               ","help               "));
        listIconos.add(new Icono(134, "icon-help-2             ","help-2             "));
        listIconos.add(new Icono(135, "icon-blocked            ","blocked            "));
        listIconos.add(new Icono(136, "icon-cancel             ","cancel             "));
        listIconos.add(new Icono(137, "icon-cancel-2           ","cancel-2           "));
        listIconos.add(new Icono(138, "icon-checkmark          ","checkmark          "));
        listIconos.add(new Icono(139, "icon-minus-2            ","minus-2            "));
        listIconos.add(new Icono(140, "icon-plus-2             ","plus-2             "));
        listIconos.add(new Icono(141, "icon-enter              ","enter              "));
        listIconos.add(new Icono(142, "icon-exit               ","exit               "));
        listIconos.add(new Icono(143, "icon-loop               ","loop               "));
        listIconos.add(new Icono(144, "icon-arrow-up-left      ","arrow-up-left      "));
        listIconos.add(new Icono(145, "icon-arrow-up           ","arrow-up           "));
        listIconos.add(new Icono(146, "icon-arrow-up-right     ","arrow-up-right     "));
        listIconos.add(new Icono(147, "icon-arrow-right        ","arrow-right        "));
        listIconos.add(new Icono(148, "icon-arrow-down-right   ","arrow-down-right   "));
        listIconos.add(new Icono(149, "icon-arrow-down         ","arrow-down         "));
        listIconos.add(new Icono(150, "icon-arrow-down-left    ","arrow-down-left    "));
        listIconos.add(new Icono(151, "icon-arrow-left         ","arrow-left         "));
        listIconos.add(new Icono(152, "icon-arrow-up-2         ","arrow-up-2         "));
        listIconos.add(new Icono(153, "icon-arrow-right-2      ","arrow-right-2      "));
        listIconos.add(new Icono(154, "icon-arrow-down-2       ","arrow-down-2       "));
        listIconos.add(new Icono(155, "icon-arrow-left-2       ","arrow-left-2       "));
        listIconos.add(new Icono(156, "icon-arrow-up-3         ","arrow-up-3         "));
        listIconos.add(new Icono(157, "icon-arrow-right-3      ","arrow-right-3      "));
        listIconos.add(new Icono(158, "icon-arrow-down-3       ","arrow-down-3       "));
        listIconos.add(new Icono(159, "icon-arrow-left-3       ","arrow-left-3       "));
        listIconos.add(new Icono(160, "icon-menu               ","menu               "));
        listIconos.add(new Icono(161, "icon-enter-2            ","enter-2            "));
        listIconos.add(new Icono(162, "icon-backspace          ","backspace          "));
        listIconos.add(new Icono(163, "icon-backspace-2        ","backspace-2        "));
        listIconos.add(new Icono(164, "icon-tab                ","tab                "));
        listIconos.add(new Icono(165, "icon-tab-2              ","tab-2              "));
        listIconos.add(new Icono(166, "icon-checkbox           ","checkbox           "));
        listIconos.add(new Icono(167, "icon-checkbox-unchecked ","checkbox-unchecked "));
        listIconos.add(new Icono(168, "icon-checkbox-partial   ","checkbox-partial   "));
        listIconos.add(new Icono(169, "icon-radio-checked      ","radio-checked      "));
        listIconos.add(new Icono(170, "icon-radio-unchecked    ","radio-unchecked    "));
        listIconos.add(new Icono(171, "icon-font               ","font               "));
        listIconos.add(new Icono(172, "icon-paragraph-left     ","paragraph-left     "));
        listIconos.add(new Icono(173, "icon-paragraph-center   ","paragraph-center   "));
        listIconos.add(new Icono(174, "icon-paragraph-right    ","paragraph-right    "));
        listIconos.add(new Icono(175, "icon-paragraph-justify  ","paragraph-justify  "));
        listIconos.add(new Icono(176, "icon-left-to-right      ","left-to-right      "));
        listIconos.add(new Icono(177, "icon-right-to-left      ","right-to-left      "));
        listIconos.add(new Icono(178, "icon-share              ","share              "));
        listIconos.add(new Icono(179, "icon-new-tab            ","new-tab            "));
        listIconos.add(new Icono(180, "icon-new-tab-2          ","new-tab-2          "));
        listIconos.add(new Icono(181, "icon-embed              ","embed              "));
        listIconos.add(new Icono(182, "icon-code               ","code               "));
        listIconos.add(new Icono(183, "icon-bluetooth          ","bluetooth          "));
        listIconos.add(new Icono(184, "icon-share-2            ","share-2            "));
        listIconos.add(new Icono(185, "icon-share-3            ","share-3            "));
        listIconos.add(new Icono(186, "icon-mail-2             ","mail-2             "));
        listIconos.add(new Icono(187, "icon-google             ","google             "));
        listIconos.add(new Icono(188, "icon-google-plus        ","google-plus        "));
        listIconos.add(new Icono(189, "icon-google-drive       ","google-drive       "));
        listIconos.add(new Icono(190, "icon-facebook           ","facebook           "));
        listIconos.add(new Icono(191, "icon-instagram          ","instagram          "));
        listIconos.add(new Icono(192, "icon-twitter            ","twitter            "));
        listIconos.add(new Icono(193, "icon-feed               ","feed               "));
        listIconos.add(new Icono(194, "icon-youtube            ","youtube            "));
        listIconos.add(new Icono(195, "icon-vimeo              ","vimeo              "));
        listIconos.add(new Icono(196, "icon-flickr             ","flickr             "));
        listIconos.add(new Icono(197, "icon-picassa            ","picassa            "));
        listIconos.add(new Icono(198, "icon-dribbble           ","dribbble           "));
        listIconos.add(new Icono(199, "icon-deviantart         ","deviantart         "));
        listIconos.add(new Icono(200, "icon-github             ","github             "));
        listIconos.add(new Icono(201, "icon-github-2           ","github-2           "));
        listIconos.add(new Icono(202, "icon-github-3           ","github-3           "));
        listIconos.add(new Icono(203, "icon-github-4           ","github-4           "));
        listIconos.add(new Icono(204, "icon-github-5           ","github-5           "));
        listIconos.add(new Icono(205, "icon-github-6           ","github-6           "));
        listIconos.add(new Icono(206, "icon-git                ","git                "));
        listIconos.add(new Icono(207, "icon-wordpress          ","wordpress          "));
        listIconos.add(new Icono(208, "icon-joomla             ","joomla             "));
        listIconos.add(new Icono(209, "icon-blogger            ","blogger            "));
        listIconos.add(new Icono(210, "icon-tumblr             ","tumblr             "));
        listIconos.add(new Icono(211, "icon-yahoo              ","yahoo              "));
        listIconos.add(new Icono(212, "icon-amazon             ","amazon             "));
        listIconos.add(new Icono(213, "icon-tux                ","tux                "));
        listIconos.add(new Icono(214, "icon-apple              ","apple              "));
        listIconos.add(new Icono(215, "icon-finder             ","finder             "));
        listIconos.add(new Icono(216, "icon-android            ","android            "));
        listIconos.add(new Icono(217, "icon-windows            ","windows            "));
        listIconos.add(new Icono(218, "icon-soundcloud         ","soundcloud         "));
        listIconos.add(new Icono(219, "icon-skype              ","skype              "));
        listIconos.add(new Icono(220, "icon-reddit             ","reddit             "));
        listIconos.add(new Icono(221, "icon-linkedin           ","linkedin           "));
        listIconos.add(new Icono(222, "icon-lastfm             ","lastfm             "));
        listIconos.add(new Icono(223, "icon-delicious          ","delicious          "));
        listIconos.add(new Icono(224, "icon-stumbleupon        ","stumbleupon        "));
        listIconos.add(new Icono(225, "icon-pinterest          ","pinterest          "));
        listIconos.add(new Icono(226, "icon-xing               ","xing               "));
        listIconos.add(new Icono(227, "icon-flattr             ","flattr             "));
        listIconos.add(new Icono(228, "icon-foursquare         ","foursquare         "));
        listIconos.add(new Icono(229, "icon-paypal             ","paypal             "));
        listIconos.add(new Icono(230, "icon-yelp               ","yelp               "));
        listIconos.add(new Icono(231, "icon-libreoffice        ","libreoffice        "));
        listIconos.add(new Icono(232, "icon-file-pdf           ","file-pdf           "));
        listIconos.add(new Icono(233, "icon-file-openoffice    ","file-openoffice    "));
        listIconos.add(new Icono(234, "icon-file-word          ","file-word          "));
        listIconos.add(new Icono(235, "icon-file-excel         ","file-excel         "));
        listIconos.add(new Icono(236, "icon-file-powerpoint    ","file-powerpoint    "));
        listIconos.add(new Icono(237, "icon-file-zip           ","file-zip           "));
        listIconos.add(new Icono(238, "icon-file-xml           ","file-xml           "));
        listIconos.add(new Icono(239, "icon-file-css           ","file-css           "));
        listIconos.add(new Icono(240, "icon-html5              ","html5              "));
        listIconos.add(new Icono(241, "icon-html5-2            ","html5-2            "));
        listIconos.add(new Icono(242, "icon-css3               ","css3               "));
        listIconos.add(new Icono(243, "icon-chrome             ","chrome             "));
        listIconos.add(new Icono(244, "icon-firefox            ","firefox            "));
        listIconos.add(new Icono(245, "icon-IE                 ","IE                 "));
        listIconos.add(new Icono(246, "icon-opera              ","opera              "));
        listIconos.add(new Icono(247, "icon-safari             ","safari             "));
        listIconos.add(new Icono(248, "icon-IcoMoon            ","IcoMoon            "));
        listIconos.add(new Icono(249, "icon-sunrise            ","sunrise            "));
        listIconos.add(new Icono(250, "icon-sun                ","sun                "));
        listIconos.add(new Icono(251, "icon-moon               ","moon               "));
        listIconos.add(new Icono(252, "icon-sun-2              ","sun-2              "));
        listIconos.add(new Icono(253, "icon-windy              ","windy              "));
        listIconos.add(new Icono(254, "icon-wind               ","wind               "));
        listIconos.add(new Icono(255, "icon-snowflake          ","snowflake          "));
        listIconos.add(new Icono(256, "icon-cloudy             ","cloudy             "));
        listIconos.add(new Icono(257, "icon-cloud-3            ","cloud-3            "));
        listIconos.add(new Icono(258, "icon-weather            ","weather            "));
        listIconos.add(new Icono(259, "icon-weather-2          ","weather-2          "));
        listIconos.add(new Icono(260, "icon-weather-3          ","weather-3          "));
        listIconos.add(new Icono(261, "icon-lines              ","lines              "));
        listIconos.add(new Icono(262, "icon-cloud-4            ","cloud-4            "));
        listIconos.add(new Icono(263, "icon-lightning-2        ","lightning-2        "));
        listIconos.add(new Icono(264, "icon-lightning-3        ","lightning-3        "));
        listIconos.add(new Icono(265, "icon-rainy              ","rainy              "));
        listIconos.add(new Icono(266, "icon-rainy-2            ","rainy-2            "));
        listIconos.add(new Icono(267, "icon-windy-2            ","windy-2            "));
        listIconos.add(new Icono(268, "icon-windy-3            ","windy-3            "));
        listIconos.add(new Icono(269, "icon-snowy              ","snowy              "));
        listIconos.add(new Icono(270, "icon-snowy-2            ","snowy-2            "));
        listIconos.add(new Icono(271, "icon-snowy-3            ","snowy-3            "));
        listIconos.add(new Icono(272, "icon-weather-4          ","weather-4          "));
        listIconos.add(new Icono(273, "icon-cloudy-2           ","cloudy-2           "));
        listIconos.add(new Icono(274, "icon-cloud-5            ","cloud-5            "));
        listIconos.add(new Icono(275, "icon-lightning-4        ","lightning-4        "));
        listIconos.add(new Icono(276, "icon-sun-3              ","sun-3              "));
        listIconos.add(new Icono(277, "icon-moon-2             ","moon-2             "));
        listIconos.add(new Icono(278, "icon-cloudy-3           ","cloudy-3           "));
        listIconos.add(new Icono(279, "icon-cloud-6            ","cloud-6            "));
        listIconos.add(new Icono(280, "icon-cloud-7            ","cloud-7            "));
        listIconos.add(new Icono(281, "icon-lightning-5        ","lightning-5        "));
        listIconos.add(new Icono(282, "icon-rainy-3            ","rainy-3            "));
        listIconos.add(new Icono(283, "icon-rainy-4            ","rainy-4            "));
        listIconos.add(new Icono(284, "icon-windy-4            ","windy-4            "));
        listIconos.add(new Icono(285, "icon-windy-5            ","windy-5            "));
        listIconos.add(new Icono(286, "icon-snowy-4            ","snowy-4            "));
        listIconos.add(new Icono(287, "icon-snowy-5            ","snowy-5            "));
        listIconos.add(new Icono(288, "icon-weather-5          ","weather-5          "));
        listIconos.add(new Icono(289, "icon-cloudy-4           ","cloudy-4           "));
        listIconos.add(new Icono(290, "icon-lightning-6        ","lightning-6        "));
        listIconos.add(new Icono(291, "icon-thermometer        ","thermometer        "));
        listIconos.add(new Icono(292, "icon-compass-2          ","compass-2          "));
        listIconos.add(new Icono(293, "icon-none               ","none               "));
        listIconos.add(new Icono(294, "icon-Celsius            ","Celsius            "));
        listIconos.add(new Icono(295, "icon-Fahrenheit         ","Fahrenheit         "));
        listIconos.add(new Icono(296, "icon-forrst             ","forrst             "));
        listIconos.add(new Icono(297, "icon-headphones         ","headphones         "));
        listIconos.add(new Icono(298, "icon-bug                ","bug                "));
        listIconos.add(new Icono(299, "icon-cart-2             ","cart-2             "));
        listIconos.add(new Icono(300, "icon-earth              ","earth              "));
        listIconos.add(new Icono(301, "icon-battery            ","battery            "));
        listIconos.add(new Icono(302, "icon-list               ","list               "));
        listIconos.add(new Icono(303, "icon-grid               ","grid               "));
        listIconos.add(new Icono(304, "icon-alarm              ","alarm              "));
        listIconos.add(new Icono(305, "icon-location-2         ","location-2         "));
        listIconos.add(new Icono(306, "icon-pointer            ","pointer            "));
        listIconos.add(new Icono(307, "icon-diary              ","diary              "));
        listIconos.add(new Icono(308, "icon-eye-2              ","eye-2              "));
        listIconos.add(new Icono(309, "icon-console            ","console            "));
        listIconos.add(new Icono(310, "icon-location-3         ","location-3         "));
        listIconos.add(new Icono(311, "icon-move               ","move               "));
        listIconos.add(new Icono(312, "icon-monitor            ","monitor            "));
        listIconos.add(new Icono(313, "icon-mobile-2           ","mobile-2           "));
        listIconos.add(new Icono(314, "icon-switch             ","switch             "));
        listIconos.add(new Icono(315, "icon-star-4             ","star-4             "));
        listIconos.add(new Icono(316, "icon-address-book       ","address-book       "));
        listIconos.add(new Icono(317, "icon-shit               ","shit               "));
        listIconos.add(new Icono(318, "icon-cone               ","cone               "));
        listIconos.add(new Icono(319, "icon-credit-card        ","credit-card        "));
        listIconos.add(new Icono(320, "icon-type               ","type               "));
        listIconos.add(new Icono(321, "icon-volume             ","volume             "));
        listIconos.add(new Icono(322, "icon-volume-2           ","volume-2           "));
        listIconos.add(new Icono(323, "icon-locked-2           ","locked-2           "));
        listIconos.add(new Icono(324, "icon-warning            ","warning            "));
        listIconos.add(new Icono(325, "icon-info               ","info               "));
        listIconos.add(new Icono(326, "icon-filter             ","filter             "));
        listIconos.add(new Icono(327, "icon-bookmark-3         ","bookmark-3         "));
        listIconos.add(new Icono(328, "icon-bookmark-4         ","bookmark-4         "));
        listIconos.add(new Icono(329, "icon-stats              ","stats              "));
        listIconos.add(new Icono(330, "icon-compass-3          ","compass-3          "));
        listIconos.add(new Icono(331, "icon-keyboard           ","keyboard           "));
        listIconos.add(new Icono(332, "icon-award-fill         ","award-fill         "));
        listIconos.add(new Icono(333, "icon-award-stroke       ","award-stroke       "));
        listIconos.add(new Icono(334, "icon-beaker-alt         ","beaker-alt         "));
        listIconos.add(new Icono(335, "icon-beaker             ","beaker             "));
        listIconos.add(new Icono(336, "icon-move-vertical      ","move-vertical      "));
        listIconos.add(new Icono(337, "icon-move-horizontal    ","move-horizontal    "));
        listIconos.add(new Icono(338, "icon-steering-wheel     ","steering-wheel     "));
        listIconos.add(new Icono(339, "icon-volume-3           ","volume-3           "));
        listIconos.add(new Icono(340, "icon-volume-mute        ","volume-mute        "));
        listIconos.add(new Icono(341, "icon-play               ","play               "));
        listIconos.add(new Icono(342, "icon-pause              ","pause              "));
        listIconos.add(new Icono(343, "icon-stop               ","stop               "));
        listIconos.add(new Icono(344, "icon-eject              ","eject              "));
        listIconos.add(new Icono(345, "icon-first              ","first              "));
        listIconos.add(new Icono(346, "icon-last               ","last               "));
        listIconos.add(new Icono(347, "icon-play-alt           ","play-alt           "));
        listIconos.add(new Icono(348, "icon-battery-empty      ","battery-empty      "));
        listIconos.add(new Icono(349, "icon-battery-half       ","battery-half       "));
        listIconos.add(new Icono(350, "icon-battery-full       ","battery-full       "));
        listIconos.add(new Icono(351, "icon-battery-charging   ","battery-charging   "));
        listIconos.add(new Icono(352, "icon-left-quote         ","left-quote         "));
        listIconos.add(new Icono(353, "icon-right-quote        ","right-quote        "));
        listIconos.add(new Icono(354, "icon-left-quote-alt     ","left-quote-alt     "));
        listIconos.add(new Icono(355, "icon-right-quote-alt    ","right-quote-alt    "));
        listIconos.add(new Icono(356, "icon-smiley             ","smiley             "));
        listIconos.add(new Icono(357, "icon-umbrella           ","umbrella           "));
        listIconos.add(new Icono(358, "icon-info-2             ","info-2             "));
        listIconos.add(new Icono(359, "icon-chart-alt          ","chart-alt          "));
        listIconos.add(new Icono(360, "icon-floppy             ","floppy             "));
        listIconos.add(new Icono(361, "icon-at                 ","at                 "));
        listIconos.add(new Icono(362, "icon-hash               ","hash               "));
        listIconos.add(new Icono(363, "icon-pilcrow            ","pilcrow            "));
        listIconos.add(new Icono(364, "icon-fullscreen-alt     ","fullscreen-alt     "));
        listIconos.add(new Icono(365, "icon-fullscreen-exit-alt","fullscreen-exit-alt"));
        listIconos.add(new Icono(366, "icon-layers-alt         ","layers-alt         "));
        listIconos.add(new Icono(367, "icon-layers             ","layers             "));
        listIconos.add(new Icono(368, "icon-rainbow            ","rainbow            "));
        listIconos.add(new Icono(369, "icon-air                ","air                "));
        listIconos.add(new Icono(370, "icon-spin               ","spin               "));
        listIconos.add(new Icono(371, "icon-auction            ","auction            "));
        listIconos.add(new Icono(372, "icon-dollar             ","dollar             "));
        listIconos.add(new Icono(373, "icon-dollar-2           ","dollar-2           "));
        listIconos.add(new Icono(374, "icon-coins              ","coins              "));
        listIconos.add(new Icono(375, "icon-file-2             ","file-2             "));
        listIconos.add(new Icono(376, "icon-file-3             ","file-3             "));
        listIconos.add(new Icono(377, "icon-file-4             ","file-4             "));
        listIconos.add(new Icono(378, "icon-files              ","files              "));
        listIconos.add(new Icono(379, "icon-phone-2            ","phone-2            "));
        listIconos.add(new Icono(380, "icon-tablet             ","tablet             "));
        listIconos.add(new Icono(381, "icon-monitor-2          ","monitor-2          "));
        listIconos.add(new Icono(382, "icon-window             ","window             "));
        listIconos.add(new Icono(383, "icon-tv                 ","tv                 "));
        listIconos.add(new Icono(384, "icon-camera-3           ","camera-3           "));
        listIconos.add(new Icono(385, "icon-image              ","image              "));
        listIconos.add(new Icono(386, "icon-open               ","open               "));
        listIconos.add(new Icono(387, "icon-sale               ","sale               "));
        listIconos.add(new Icono(388, "icon-direction          ","direction          "));
        listIconos.add(new Icono(389, "icon-medal              ","medal              "));
        listIconos.add(new Icono(390, "icon-medal-2            ","medal-2            "));
        listIconos.add(new Icono(391, "icon-satellite          ","satellite          "));
        listIconos.add(new Icono(392, "icon-discout            ","discout            "));
        listIconos.add(new Icono(393, "icon-barcode            ","barcode            "));
        listIconos.add(new Icono(394, "icon-ticket             ","ticket             "));
        listIconos.add(new Icono(395, "icon-shipping           ","shipping           "));
        listIconos.add(new Icono(396, "icon-globe              ","globe              "));
        listIconos.add(new Icono(397, "icon-anchor             ","anchor             "));
        listIconos.add(new Icono(398, "icon-pop-out            ","pop-out            "));
        listIconos.add(new Icono(399, "icon-pop-in             ","pop-in             "));
        listIconos.add(new Icono(400, "icon-resize             ","resize             "));
        listIconos.add(new Icono(401, "icon-battery-2          ","battery-2          "));
        listIconos.add(new Icono(402, "icon-battery-3          ","battery-3          "));
        listIconos.add(new Icono(403, "icon-battery-4          ","battery-4          "));
        listIconos.add(new Icono(404, "icon-battery-5          ","battery-5          "));
        listIconos.add(new Icono(405, "icon-tools              ","tools              "));
        listIconos.add(new Icono(406, "icon-alarm-2            ","alarm-2            "));
        listIconos.add(new Icono(407, "icon-alarm-cancel       ","alarm-cancel       "));
        listIconos.add(new Icono(408, "icon-alarm-clock        ","alarm-clock        "));
        listIconos.add(new Icono(409, "icon-chronometer        ","chronometer        "));
        listIconos.add(new Icono(410, "icon-ruler              ","ruler              "));
        listIconos.add(new Icono(411, "icon-lamp               ","lamp               "));
        listIconos.add(new Icono(412, "icon-lamp-2             ","lamp-2             "));
        listIconos.add(new Icono(413, "icon-scissors           ","scissors           "));
        listIconos.add(new Icono(414, "icon-volume-4           ","volume-4           "));
        listIconos.add(new Icono(415, "icon-volume-5           ","volume-5           "));
        listIconos.add(new Icono(416, "icon-volume-6           ","volume-6           "));
        listIconos.add(new Icono(417, "icon-zip                ","zip                "));
        listIconos.add(new Icono(418, "icon-zip-2              ","zip-2              "));
        listIconos.add(new Icono(419, "icon-play-2             ","play-2             "));
        listIconos.add(new Icono(420, "icon-pause-2            ","pause-2            "));
        listIconos.add(new Icono(421, "icon-record             ","record             "));
        listIconos.add(new Icono(422, "icon-stop-2             ","stop-2             "));
        listIconos.add(new Icono(423, "icon-next               ","next               "));
        listIconos.add(new Icono(424, "icon-previous           ","previous           "));
        listIconos.add(new Icono(425, "icon-first-2            ","first-2            "));
        listIconos.add(new Icono(426, "icon-last-2             ","last-2             "));
        listIconos.add(new Icono(427, "icon-arrow-left-4       ","arrow-left-4       "));
        listIconos.add(new Icono(428, "icon-arrow-down-4       ","arrow-down-4       "));
        listIconos.add(new Icono(429, "icon-arrow-up-4         ","arrow-up-4         "));
        listIconos.add(new Icono(430, "icon-arrow-right-4      ","arrow-right-4      "));
        listIconos.add(new Icono(431, "icon-arrow-right-4      ","arrow-right-4      "));
        listIconos.add(new Icono(432, "icon-arrow-left-5       ","arrow-left-5       "));
        listIconos.add(new Icono(433, "icon-arrow-down-5       ","arrow-down-5       "));
        listIconos.add(new Icono(434, "icon-arrow-up-5         ","arrow-up-5         "));
        listIconos.add(new Icono(435, "icon-arrow-right-5      ","arrow-right-5      "));
        listIconos.add(new Icono(436, "icon-cc                 ","cc                 "));
        listIconos.add(new Icono(437, "icon-cc-by              ","cc-by              "));
        listIconos.add(new Icono(438, "icon-cc-nc              ","cc-nc              "));
        listIconos.add(new Icono(439, "icon-cc-nc-eu           ","cc-nc-eu           "));
        listIconos.add(new Icono(440, "icon-cc-nc-jp           ","cc-nc-jp           "));
        listIconos.add(new Icono(441, "icon-cc-sa              ","cc-sa              "));
        listIconos.add(new Icono(442, "icon-cc-nd              ","cc-nd              "));
        listIconos.add(new Icono(443, "icon-cc-pd              ","cc-pd              "));
        listIconos.add(new Icono(444, "icon-cc-zero            ","cc-zero            "));
        listIconos.add(new Icono(445, "icon-cc-share           ","cc-share           "));
        listIconos.add(new Icono(446, "icon-cc-share-2         ","cc-share-2         "));
        listIconos.add(new Icono(447, "icon-cycle              ","cycle              "));
        listIconos.add(new Icono(448, "icon-stop-3             ","stop-3             "));
        listIconos.add(new Icono(449, "icon-stats-2            ","stats-2            "));
        listIconos.add(new Icono(450, "icon-stats-3            ","stats-3            "));
    }
    
    private void setStatus(){
        listStatus = new HashMap<String,String>();
        listStatus.put("Alta","0");
        listStatus.put("Baja","1");
        
    }
    
    private void setTipoMenus(){
        tiposMenus = new HashMap<String, String>();
        tiposMenus.put("Menu","0");
        tiposMenus.put("SubMenu","1");
    }
}
